image: node:latest
pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: yarn
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public