image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    untracked: true
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv dist public
  artifacts:
    paths:
      - public
